backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "data"
    label: "Dados"
    files:
      - name: "products"
        label: "Produtos"
        file: "data/products.json"
        fields:
          - name: "products"
            label: "Lista de Produtos"
            widget: "list"
            fields:
              - {label: "Código", name: "code", widget: "string"}
              - {label: "Preço", name: "price", widget: "string", required: false}
              - {label: "Descrição", name: "desc", widget: "text", required: false}
              - {label: "Categoria", name: "category", widget: "select", options: ["ceramica", "resina"], default: "ceramica"}
              - {label: "WhatsApp Link", name: "whatsapp", widget: "string"}